# version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./learnerReportCS_backend
    image : ankit200193/learnerreport_backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - ATLAS_URI=mongodb://mongo:27017/learnerCS
    restart: always

  frontend:
    build:
      context: ./learnerReportCS_frontend
    image : ankit200193/learnerreport_frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000
    stdin_open: true
    tty: true

volumes:
  mongo-data:
