# backend-deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: learner-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ankit200193/learnerreport_backend
          ports:
            - containerPort: 3000
          env:
            - name: ATLAS_URI
              value: "mongodb://mongo:27017/learnerdb"
            - name: HASH_KEY
              value: "thisIsMyHashKey"
            - name: JWT_SECRET_KEY
              value: "thisIsMyJwtSecretKey"

             
---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
