# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: learner-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ankit200193/learnerreport_backend:01
          ports:
            - containerPort: 5000
          env:
            - name: ATLAS_URI
              value: "mongodb://mongo:27017/learnerCS"
            - name: HASH_KEY
              value: "thisIsMyHashKey"
            - name: JWT_SECRET_KEY
              value: "thisIsMyJwtSecretKey"
            - name: PORT
              value: "5000"

---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: learner-app
spec:
  selector:
    app: backend
  type: NodePort

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30027
