# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: learner-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ankit200193/learnerreport_frontend:01
          ports:
            - containerPort: 3000
          env:
          - name: REACT_APP_API_BASE_URL
            value: http://13.233.18.200:30027 # it has to be worker node public IP + backed serice nodeport

---
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: learner-app
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
