apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.containerPort }}
      targetPort: {{ .Values.mongo.containerPort }}
  clusterIP: None
